### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [devanshiu/Flixster#1]
It looks like your video walkthrough doesn't seem to show the movie displayed in landscape mode and to view details of the movie including ratings and popularity within a separate activity. Can you update this and resubmit?

**Comment by devanshiu** [comment]
Hi,

Sorry for the delayed response. I have been having a lot of laptop issues with my Lenovo and just realized that the walkthrough I had submitted earlier cut off at a certain point and did not show the landscape view or movie details page. I decided to try out a different MP4 to gif online converter, and it should be working now!

- Devanshi

On Jun 27, 2020, at 6:27 AM, CodePath Reviewers <notifications@github.com> wrote:

﻿

It looks like your video walkthrough doesn't seem to show the movie displayed in landscape mode and to view details of the movie including ratings and popularity within a separate activity. Can you update this and resubmit?

**Comment by codepathreview** [comment]
The video walkthrough now shows a view displayed in landscape mode.

However, it seems like the details of the movie's popularity still doesn't show in the video walkthrough. This detail is alongside with the movie's ratings and synopsis when you selected the movie in the list. It is one of the required user stories, you can refer to #4 in the Assignment tab. Let us know if you have further clarifications. clarifications. 
/cc @codepathreview

**Comment by devanshiu** [comment]
Popularity should show up now! Sorry, I was under the impression that ratings and popularity were referring to the same metric, but it should be updated now.

On Jun 28, 2020, at 11:50 PM, CodePath Reviewers <notifications@github.com> wrote:

﻿

The video walkthrough now shows a view displayed in landscape mode.

However, it seems like the details of the movie's popularity still doesn't show in the video walkthrough. This detail is alongside with the movie's ratings and synopsis when you selected the movie in the list. It is one of the required user stories, you can refer to #4 in the Assignment tab. Let us know if you have further clarifications. clarifications.
/cc @codepathreview<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcodepathreview&data=02%7C01%7Cdevanshi.udeshi.22%40dartmouth.edu%7Cb205f2dfcb1040e5e77c08d81bf8b7db%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C637290102339978550&sdata=Dcl%2BN3I2UjjMeULmm7QwTx2zcLzAAYas%2Fieg%2Bqr9ll8%3D&reserved=0>
